---
title: "data_prep"
author: "Cam Reimer"
date: "3/14/2023"
output: html_document
---

```{r load in data}
#navigate to directory 
setwd("C:/Users/camer/OneDrive/Documents/SPH/PRESTO")
#load in packages 
library(tidyverse)
library(lubridate)
library(dplyr)
library(labelled)
library(tidyr)
library (sas7bdat)
library(haven)
#load in functions
source("~/R/PRESTO_sleep/data_prep_functions.R")
#load in data
data_full <- read_sas("ndvi_mental_001.sas7bdat")
```

```{r Data Wrangling, Add NDVI}
years <- 2012:2019
buffers <- c(50,100,250,500)

#select important columns
data = data_full[c("StudyID", "Country", "ageatqstn", "b_race_ethnic_census", "b_educ", "b_income", "ct_HHinc", "ct_lths", "ct_urban", "pss_score", "b_mdi_score",  "b_finisheddate", "b_hourssleep", "b_currentjob", "b_jobhrsperweek", generate_all_ndvi_colnames(years,buffers))]

#get NDVI - This may take a while
data <- add_ndvi(data, id_colname = "StudyID", date_colname = "b_finisheddate", buffers=buffers)

#categorize ct_urban
data <- add_urban_cat(data)
#add binary outcome 
data$hrssleep_cat <- data$b_hourssleep >= 7 

#format exercise composite 
exer_names <- c('b_walkwork', 'b_walkexer', 'b_walktrans', 'b_bike', 'b_freeweights', 'b_jogswimraq', 'b_aerobics', 'b_garden') #not including 'b_yoga'
pa_old <- as.matrix(data_full[exer_names])
pa_new <- matrix(NA, nrow = dim(pa_old)[1], ncol = dim(pa_old)[2])
pa_adjusted <- matrix(NA, nrow = dim(pa_old)[1], ncol = dim(pa_old)[2])
colnames(pa_adjusted) <- exer_names

scaling_factors <- c(2.0, 3.8, 2.5, 7.5, 4.5, 7.0, 6.5, 2.5) #2.5 for b_yoga

for(i in 1:dim(pa_new)[2]){
 pa_new[,i] <- case_when(
  pa_old[,i] == 1 ~ 0,
  pa_old[,i] == 2 ~ 0.5,
  pa_old[,i] == 3 ~ 1,
  pa_old[,i] == 4 ~ 2,
  pa_old[,i] == 5 ~ 3.5,
  pa_old[,i] == 6 ~ 5.5,
  pa_old[,i] == 7 ~ 7,
  #TRUE ~ 0         
) 
 pa_adjusted[,i] <- pa_new[,i] * scaling_factors[i]
}

data$b_totalmet <- apply(pa_adjusted, 1, sum)


rm(data_full)
```

```{r Check for missingness}
#remove missing data 
data_final = na.omit(data)
dropped <- subset(data, !(data$StudyID %in% data_final$StudyID))

#check counts of missing data 
missing_counts <- colMeans(is.na(data)) * dim(data)[1]
missing_counts <- append(missing_counts, dim(data)[1] - dim(na.omit(data[,grep("ndvi", names(data))]))[1])
missing_counts <- append(missing_counts, dim(data)[1] - dim(data_final)[1])
miss <- as.matrix(missing_counts)
colnames(miss) <- "count"
rownames(miss)[c(dim(miss)[1]-1,dim(miss)[1])] <- c("All NDVI", "Total")
miss
rm(data)
```

```{r Get quantiles and assign factors}
#Get IQR for analysis 
data_final <- get_ndvi_iqr(data_final)
#Create Quantiles of NDVI IQR
data_final <- get_ndvi_iqr_quartiles(data_final)
#Create Quantiles for NSES
data_final <- data_final %>%
  mutate(ct_HHinc_quantile = ntile(ct_HHinc, 3))

#Add binary outcome measure
data_final$hrssleep <- as.numeric(data_final$hrssleep_cat)

#turn variables into factors 
factor_vars <- c("b_race_ethnic_census", "b_educ", "b_income", "ct_urban_cat", "b_currentjob", names(data_final[grep("quantile", names(data_final))]))
data_final[factor_vars] <- lapply(data_final[factor_vars], factor)

dropped[c("b_race_ethnic_census", "b_educ", "b_income", "ct_urban_cat", "b_currentjob")] <- lapply(dropped[c("b_race_ethnic_census", "b_educ", "b_income", "ct_urban_cat", "b_currentjob")], factor)
```

```{r Create subsets}
urban = subset(data_final, ct_urban_cat == 1)
rural = subset(data_final, ct_urban_cat == 0)

#use census tract income as a proxy for Neighborhood Socioeconomic Status
NSES1 = subset(data_final, ct_HHinc_quantile == 1)
NSES2 = subset(data_final, ct_HHinc_quantile == 2)
NSES3 = subset(data_final, ct_HHinc_quantile == 3)

#combined stratification
NSES1_urban = subset(data_final, ct_HHinc_quantile == 1 & ct_urban_cat ==1)
NSES2_urban = subset(data_final, ct_HHinc_quantile == 2 & ct_urban_cat ==1)
NSES3_urban = subset(data_final, ct_HHinc_quantile == 3 & ct_urban_cat ==1)
NSES1_rural = subset(data_final, ct_HHinc_quantile == 1 & ct_urban_cat ==0)
NSES2_rural = subset(data_final, ct_HHinc_quantile == 2 & ct_urban_cat ==0)
NSES3_rural = subset(data_final, ct_HHinc_quantile == 3 & ct_urban_cat ==0)

data <- data_final
rm(data_final)
```

```{r Export data}
save(data, urban, rural, NSES1, NSES2, NSES3, NSES1_urban, NSES2_urban, NSES3_urban, NSES1_rural, NSES2_rural, NSES3_rural, file = "C:/Users/camer/OneDrive/Documents/SPH/PRESTO/data/data_processed_sleep.RData")

save(dropped, file = "C:/Users/camer/OneDrive/Documents/SPH/PRESTO/data/dropped_sleep.RData")
#write_csv(data_final, "C:/Users/camer/OneDrive/Documents/SPH/PRESTO/data/data_processed.csv")
```


