---
title: "splines"
author: "Cam Reimer"
date: "2023-03-18"
output: html_document
---

```{r}
#load in packages 
library(tableone)
library(tidyverse)
library(lubridate)
library(dplyr)
library(labelled)
library(mgcv)
#load in data
load("C:/Users/camer/OneDrive/Documents/SPH/PRESTO/data/data_processed_sleep.RData")
```

#Exploratory analysis - Logistic regression

```{r}
par(mfrow=c(1,2))
df <- data
spline1 <- gam(as.numeric(b_hourssleep >=7)~ s(ndvi_100_amax_iqr, fx=TRUE, k=3) + ageatqstn + b_race_ethnic_census + b_educ + b_income + b_currentjob + b_jobhrsperweek + ct_HHinc + ct_lths , data = df, na.action=na.omit )
plot(spline1, las=1, ylab="Sleep", xlab= "Green space")
legend("topleft", c("Spline", "95%CI"), lty=1:2, box.lty=1, cex=0.9)
mtext ("Hours of Sleep >= 7", side=3, line=0.4, adj=-0.08, cex=0.9)

spline2 <- gam(b_hourssleep ~ s(ndvi_100_amax_iqr, fx=TRUE, k=3) + ageatqstn + b_race_ethnic_census + b_educ + b_income + b_currentjob + b_jobhrsperweek + ct_HHinc + ct_lths , data = df, na.action=na.omit )
plot(spline2, las=1, ylab="Sleep", xlab= "Green space")
legend("topleft", c("Spline", "95%CI"), lty=1:2, box.lty=1, cex=0.9)
mtext ("Horus of Sleep", side=3, line=0.4, adj=-0.08, cex=0.9)
```

#Model 1
```{r}
df <- data
df$hrssleep <- as.numeric(df$hrssleep_cat)
model1 <- glm(hrssleep ~ ndvi_100_smax_iqr + ageatqstn + b_race_ethnic_census, data = df, family = "binomial")
summary(model1)
```

#Model 2
```{r}
df <- data 
df$hrssleep <- as.numeric(df$hrssleep_cat)
model2 <- glm(hrssleep ~ ndvi_100_smax_iqr + ageatqstn + b_race_ethnic_census + b_educ + b_income, data = df, family = "binomial")
summary(model2)

```

#Model 3
```{r}
df <- data 
df$hrssleep <- as.numeric(df$hrssleep_cat)
model3 <- glm(hrssleep ~ ndvi_100_smax_iqr + ageatqstn + b_race_ethnic_census + b_educ + b_income + ct_HHinc + ct_lths, data = df, family = "binomial")
summary(model3)
```

#Model 4 
```{r}
df <- data
df$hrssleep <- as.numeric(df$hrssleep_cat)
model4 <- glm(hrssleep ~ ndvi_100_smax_iqr + ageatqstn + b_race_ethnic_census + b_currentjob + b_jobhrsperweek, data = df, family = "binomial")
summary(model4)
```

#Model 5
```{r}
df <- data
#df$hrssleep <- as.numeric(df$hrssleep_cat)
df$hrssleep <- as.numeric(df$b_hourssleep>=7)
model5 <- glm(hrssleep ~ ndvi_100_amax_iqr + ageatqstn + b_race_ethnic_census + b_currentjob + b_jobhrsperweek + b_educ + b_income + b_totalmet, data = df, family = "binomial")
summary(model5)

#model5_OR <- exp(cbind(OR = coef(model5), confint(model5)))
```

#Model 6
```{r}
#df <- subset(data, data$b_hourssleep <= 10)
df <- data
df$hrssleep <- as.numeric(df$b_hourssleep >= 7 )
model6 <- glm(hrssleep ~ ndvi_100_amax_iqr + ageatqstn + b_race_ethnic_census + b_currentjob + b_jobhrsperweek + b_educ + b_income + ct_HHinc + ct_lths, data = df, family = "binomial")
summary(model6)
model6_out <- exp(cbind(OR = coef(model6), confint(model6)))[2,]
model6_out #OR excluding long sleepers 0.9186 CI: 0.8586,0.9825
```

```{r}
df <- NSES1
df$hrssleep <- as.numeric(df$hrssleep_cat)
model6_NSES1 <- glm(hrssleep ~ ndvi_100_amax_iqr + ageatqstn + b_race_ethnic_census + b_currentjob + b_jobhrsperweek + b_educ + b_income + ct_lths, data = df, family = "binomial")
#summary(model6_NSSE1)
df <- NSES3
df$hrssleep <- as.numeric(df$hrssleep_cat)
model6_NSES3 <- glm(hrssleep ~ ndvi_100_amax_iqr + ageatqstn + b_race_ethnic_census + b_currentjob + b_jobhrsperweek + b_educ + b_income + ct_lths, data = df, family = "binomial")
#summary(model6_NSES3)

model6_out <- exp(cbind(OR = coef(model6), confint(model6)))[2,]
model6_NSES1_out <- exp(cbind(OR = coef(model6_NSES1), confint(model6_NSES1)))[2,]
model6_NSES3_out <- exp(cbind(OR = coef(model6_NSES3), confint(model6_NSES3)))[2,]
                              
out <- rbind(full_sample = model6_out, NSES1 = model6_NSES1_out, NSES3 = model6_NSES3_out)
out
#round((1-out)*100,2)  #convert to percentages for abstract

```

```{r}
df <- urban
df$hrssleep <- as.numeric(df$hrssleep_cat) 
model6_urban <- glm(hrssleep ~ ndvi_100_amax_iqr + ageatqstn + b_race_ethnic_census + b_currentjob + b_jobhrsperweek + b_educ + b_income + ct_HHinc + ct_lths, data = df, family = "binomial")
summary(model6_urban)

df <- rural
df$hrssleep <- as.numeric(df$hrssleep_cat)
model6_rural <- glm(hrssleep ~ ndvi_100_amax_iqr + ageatqstn + b_race_ethnic_census + b_currentjob + b_jobhrsperweek + b_educ + b_income + ct_HHinc + ct_lths, data = df, family = "binomial")
summary(model6_rural)

```

#Practice plotting 
```{r}
df = data
df$hrssleep <- as.numeric(df$hrssleep_cat) 
model <- glm(hrssleep ~ ndvi_100_amax_iqr + ageatqstn + b_jobhrsperweek, data = df, family = "binomial")
summary(model)
newdata <- data.frame(ndvi_100_amax_iqr=seq(min(df$ndvi_100_amax_iqr), max(df$ndvi_100_amax_iqr),len=500), ageatqstn=seq(min(df$ageatqstn), max(df$ageatqstn),len=500), b_jobhrsperweek = seq(min(df$b_jobhrsperweek),max(df$b_jobhrsperweek), len=500))
newdata$vs = predict(model, newdata, type="response")
plot(hrssleep ~ ndvi_100_amax_iqr, data=df, col="steelblue")
lines(vs ~ ndvi_100_amax_iqr, newdata, lwd=2)

```

```{r}
df <- data[c('ageatqstn','b_jobhrsperweek', 'ct_HHinc', 'ct_lths', 'ndvi_100_amax_iqr', 'b_hourssleep')]
cor(df)

```

```{r}
#model6 <- glm(hrssleep ~ ndvi_100_amax_iqr + ageatqstn + b_race_ethnic_census + b_currentjob + b_jobhrsperweek + b_educ + b_income + ct_HHinc + ct_lths, data = df, family = "binomial")
x = c('ageatqstn', 'b_race_ethnic_census', 'b_currentjob', 'b_jobhrsperweek', 'b_educ', 'b_income', 'ct_HHinc', 'ct_lths')
ndvi_measure = 'amax'
buffer = 100
y = 'hrssleep'

glmfun<-function(data,y,buffer,x, ndvi_measure){
  # format function call 
  xname = paste(c(paste0("ndvi_",as.character(buffer), "_", as.character(ndvi_measure),"_iqr"),x) , collapse = " + ")
  formula1<-as.formula(paste(y,"~",xname))
  glm.fit<-do.call("glm",list(data=quote(data),family = 'binomial', formula1))
  out <- exp(cbind(OR = coef(glm.fit), confint(glm.fit)))[2,]
  return(out)
}

tmp <- glmfun(df,y, buffer, x, ndvi_measure)
#summary(tmp)
```
